server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: hxj.qxm.1324
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  group:
    group1: com.icdats.controller
  level:
    group1: error

